# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci --force
    - run: npm i expo-cli --force
    - run: npm run test
    
    - name: Cypress
      uses: cypress-io/github-action@v4.2.0
      with:
        install-command: npm ci --force
        start: npm run web
        wait-on: 'http://localhost:19006'
    - name: Install Postman CLI
      run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
    - name: Login to Postman CLI
      run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
    - name: Run API tests
      run: |
          postman collection run "23780244-8320a87b-617b-425e-82dc-5b019508654a" -e "23780244-7ecefb7f-0c95-4d63-93c9-477fdf680ec9"
    - run: npm run eject

